import type { Metadata } from "next";
import Layout from "@/components/Layout";
import { Protect } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Protect
      permission="org:dashboard:access"
      fallback={
        <div className="flex min-h-screen justify-center items-center flex-col gap-4">
          <p className="text-center">
            Nie masz odpowiednich uprawnień. Jeżeli potrzebujesz pomocy
            skontaktuj się z administratorem.
          </p>
          <Button asChild>
            <Link href="/">Powrót</Link>
          </Button>
        </div>
      }
    >
      <Layout>{children}</Layout>
    </Protect>
  );
}
